### ISSUE TITLE
PCF8591 + PCF8574 = error: '...' does not name a type

### ISSUE THREAD

**Issue by franzuu** [xreef/PCF8591_library#2]
Hi, thank you for the great work with this library! 
Unfortunately I have troubles getting this library and one of your other library (for PCF8574) to work together properly.
If I include both libraries, only the first one goes pass the compiler, but for the other compiler shows error.
#include "Arduino.h"
#include "PCF8574.h"          
#include "PCF8591.h"
PCF8574 pcf8574(0x21, SDA_PIN, SCL_PIN);            
PCF8591 pcf8591(0x48, SDA_PIN, SCL_PIN);

One or the other causes error (I am using Atom+PlatformIO)
If first include is PCF8591, then the error will be:
error: 'PCF8574' does not name a type

and if I change the order of includes (first include is PCF8574), then the error is inverted:
error: 'PCF8591' does not name a type

Do you know what may cause this problem?

**Comment by xreef** [comment]
I think there was a bug, can you retry now and tell me if it's resolved.
(Download PCF8574 and PFC8591 library and retry plz).
Thanks

**Comment by franzuu** [comment]
Thanks, it seems the bug is gone now. Now compiler likes both libraries together 👍 Great work!

**Comment by playaspec** [comment]
Sure would be cool to know what it was.
